class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startt'
        self.MirrorCommand = 'mirrorr'
        self.UnzipMirrorCommand = 'unzipmirrorr'
        self.TarMirrorCommand = 'tarmirrorr'
        self.CancelMirror = 'cancell'
        self.CancelAllCommand = 'cancelalll'
        self.ListCommand = 'listt'
        self.StatusCommand = 'statuss'
        self.AuthorizedUsersCommand = 'userss'
        self.AuthorizeCommand = 'authorizee'
        self.UnAuthorizeCommand = 'unauthorizee'
        self.AddSudoCommand = 'addsudoo'
        self.RmSudoCommand = 'rmsudoo'
        self.PingCommand = 'pingg'
        self.RestartCommand = 'restartt'
        self.StatsCommand = 'statss'
        self.HelpCommand = 'helpp'
        self.LogCommand = 'llog'
        self.SpeedCommand = 'speedtestt'
        self.CloneCommand = 'clonee'
        self.CountCommand = 'countt'
        self.WatchCommand = 'watcch'
        self.TarWatchCommand = 'tarwatchh'
        self.DeleteCommand = 'dell'
        self.UsageCommand = 'usaage'
        self.MediaInfoCommand = 'mediainfoo'
        self.ConfigMenuCommand = 'configg'
        self.ShellCommand = 'shelll'
        self.UpdateCommand = 'updaate'
        self.ExecHelpCommand = 'exechellp'
        self.TsHelpCommand = 'tshellp'

BotCommands = _BotCommands()
